name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.9  # Specify your desired Terraform version

    - name: Initialize Terraform
      run: |
        cd jenkins-terraform-pipeline-  # Correct directory name
        terraform init

    - name: Terraform Plan
      run: |
        cd jenkins-terraform-pipeline-  # Correct directory name
        terraform plan -out=tfplan

    - name: Terraform Apply
      if: success()
      run: |
        cd jenkins-terraform-pipeline-  # Correct directory name
        terraform apply -auto-approve tfplan

    - name: Terraform Destroy
      if: failure()
      run: |
        cd jenkins-terraform-pipeline-  # Correct directory name
        terraform destroy -auto-approve
